// Auto-generated by the postman-to-k6 converter + custom config

import "./libs/shim/core.js";
import { group } from "k6";

export let options = {
  stages: [
    { duration: "30s", target: 20 },   // Ramp-up: 0 -> 20 VUs
    { duration: "1m", target: 20 },    // Carga estável em 20 VUs
    { duration: "30s", target: 50 },   // Ramp-up: 20 -> 50 VUs
    { duration: "1m", target: 50 },    // Carga estável em 50 VUs
    { duration: "30s", target: 100 },  // Ramp-up: 50 -> 100 VUs (stress)
    { duration: "1m", target: 100 },   // Stress test em 100 VUs
    { duration: "30s", target: 0 },    // Ramp-down (recuperação)
  ],
  thresholds: {
    http_req_duration: ["p(95)<1000"],   // 95% das req < 1s
    http_req_failed: ["rate<0.05"],      // menos de 5% de falhas
  },
  maxRedirects: 4,
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function () {
  group("Users", function () {
    postman[Request]({
      name: "createUser",
      method: "POST",
      address: "http://localhost:8765/user-ms/api/users",
      data: JSON.stringify({
        username: "testUser",
        email: `user${Math.random()}@example.com`,
        password: "123456"
      }),
      headers: { "Content-Type": "application/json" }
    });

    postman[Request]({
      name: "getAllUsers",
      method: "GET",
      address: "http://localhost:8765/user-ms/api/users"
    });
  });

  group("Posts", function () {
    postman[Request]({
      name: "getAllPosts",
      method: "GET",
      address: "http://localhost:8765/post-ms/api/posts"
    });

    postman[Request]({
      name: "createPost",
      method: "POST",
      address: "http://localhost:8765/post-ms/api/posts",
      data: JSON.stringify({
        content: "Post de teste",
        user: { id: 1 },
        comments: []
      }),
      headers: { "Content-Type": "application/json" }
    });
  });

  group("Likes", function () {
    postman[Request]({
      name: "createLike",
      method: "POST",
      address: "http://localhost:8765/like-ms/api/likes",
      data: JSON.stringify({
        commentId: null,
        userId: 1,
        postId: 1
      }),
      headers: { "Content-Type": "application/json" }
    });
  });

  group("Friendships", function () {
    postman[Request]({
      name: "createFriendship",
      method: "POST",
      address: "http://localhost:8765/friendship-ms/api/friendships",
      data: JSON.stringify({
        userId1: 2,
        userId2: 3,
        status: "accepted"
      }),
      headers: { "Content-Type": "application/json" }
    });
  });

  group("Comments", function () {
    postman[Request]({
      name: "createComment",
      method: "POST",
      address: "http://localhost:8765/comment-ms/api/comments",
      data: JSON.stringify({
        content: "Comentário de teste",
        userId: 1,
        postId: 1
      }),
      headers: { "Content-Type": "application/json" }
    });
  });
}
